# Generated by Django 4.1 on 2022-08-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
